services:
  - type: web
    name: your-own-chatbot
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn chatbot_project.wsgi:application
    envVars:
      - key: SECRET_KEY
        value: your-django-secret-key
      - key: DEBUG
        value: False
      - key: OPENAI_API_KEY
        value: your-openai-api-key
      - key: DATABASE_URL
        value: sqlite:///db.sqlite3
