services:
  - type: web
    name: django-chatbot
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn chatbot_project.wsgi:application
    envVars:
      - key: SECRET_KEY
        value: your_django_secret_key
      - key: DEBUG
        value: False
      - key: OPENAI_API_KEY
        value: your_openai_api_key
      - key: DATABASE_URL
        fromDatabase:
          name: chatbot-db
          property: connectionString

databases:
  - name: chatbot-db
